@startuml
class EntitiesAndComponentsManager {
}

class GameObject {
    identifier: String
    center: CGPoint
}

protocol Component {
    identifier: String
    gameObject: GameObject
}

struct Renderable implements Component {
    +image: String
    +position: CGPoint
    +size: CGSize
}

struct Animatable implements Component {
    +toAnimate: Anination
    +startAnimation(): Void
    +stopAnimation(): Void
}

struct Destroyable implements Component {
    +health: Int
    +isDestroyed: Bool
    +takeDamage(damage: Int): Int
    +effect(gameState: GameState): Effect
}

struct Collidable implements Component {
    +isCollidingWith(other: Collidable): Bool
    +handleCollision(with: Collidable): Void
    +handleCollisionOn(side: Side, with: Collidable): Void
}

struct Movable implements Component {
    +direction: Direction
    +value: Int
}

struct Droppable implements Component {
    +drop: Collectible
}

class Collectible extends GameObject {
    animatable: Animatable
}

class GameEnemy extends GameObject {
    +destroyable: Destroyable
    +movable: Movable
    +animatable: Animatable
    +droppable: Droppable
    +physicsObject: RectanglePhysicsObject
}

class GameBlock extends GameObject {
    +destroyable: Destroyable
    +movable: Movable
    +animatable: Animatable
    +droppable: Droppable
    +physicsObject: PhysicsObject
}

class GamePlayer extends GameObject {
    +destroyable: Destroyable
    +movable: Movable
    +animatable: Animatable
    +power: Power
    +physicsObject: RectanglePhysicsObject
    +renderable: Renderable
}

struct Lifetime extends Component {
    +maxLifetime: Int
    +currentLifetime: Int
}

struct Damageable extends Component {
    +damage: Int
    +onHit(gameObject: GameObject): Void
}

class Projectile extends GameObject {
    +damageable: Damageable
    +lifetime: Lifetime
    +movable: Movable
    +animatable: Animatable
    +physicsObject: CirclePhysicsObject
}

protocol PhysicsObject {
    +center: CGPoint
    +velocity: CGVector
    +acceleration: CGVector
    +mass: CGFloat

    +isCollidingWith(other: CirclePhysicsObject): Bool
    +isCollidingWith(other: RectanglePhysicsObject): Bool
    +handleCollision(with: CirclePhysicsObject): Void
    +handleCollision(with RectanglePhysicsObject): Void
}

class CirclePhysicsObject implements PhysicsObject {
    +radius: CGFloat
}

class RectanglePhysicsObject implements PhysicsObject {
    +width: CGSize
    +height: CGSize
}

EntitiesAndComponentsManager --> GameObject
EntitiesAndComponentsManager --> Component
@enduml

