@startuml

protocol Effectable {
    +effect(gameState: GameState): Effect
}

protocol Animatable {
    +toAnimate: Anination
    +startAnimation(): Void
    +stopAnimation(): Void
}

protocol Destroyable extends Effectable {
    +health: Int
    +isDestroyed: Bool
    +takeDamage(damage: Int): Int
    +effect(gameState: GameState): Effect
}

protocol Collidable {
    +isCollidingWith(other: Collidable): Bool
    +handleCollision(with: Collidable): Void
    +handleCollisionOn(side: Side, with: Collidable): Void
}

protocol Movable {
    +move(to: Direction)
}

protocol Droppable {
    +drop(): Collectible
}

protocol Collectible extends Effectable {
    +effect(gameState: GameState): Effect
}

protocol GameObjectBehaviour {
    +isAffectedByPhysics: Bool
    +isVisible: Bool

    +action(): Void
}

class Power implements Effectable {
    +effect(gameState: GameState): Effect
}

class GameEnemy implements Destroyable, GameObjectBehaviour, Movable, Animatable, Droppable {
}

class GameBlock implements Destroyable, GameObjectBehaviour, Movable, Animatable, Droppable {
}

class Effect {
    +execute(): Void
}

class GamePlayer implements GameObjectBehaviour, Collidable, Movable, Animatable {
    +health: Int
    +lives: Int
    +strength: Int
    +speed: Int
    +power: Power
}

class Projectile implements CirclePhysicsObject, Collidable, Animatable {
    +damage: Int
    +speed: Int
    +lifetime: Int
    +owner: GameObject
    +onHit(gameObject: GameObject): Void
}

class GameObjectFactory {
    +createGameObject(type: BoardObject): GameObject
}

protocol PhysicsObject {
    +center: CGPoint
    +velocity: CGVector
    +acceleration: CGVector
    +mass: CGFloat
}

class CirclePhysicsObject implements PhysicsObject {
    +radius: CGFloat
}

class RectanglePhysicsObject implements PhysicsObject {
    +width: CGSize
    +height: CGSize
}

@enduml

