@startuml
class LevelDesignerViewModel {
}

class GameViewModel {
}

class Renderer {
}

protocol Persistence {
    +saveLevel(level: Level)
    +loadLevel(levelName: string): Level
    +deleteLevel(levelName: string)
}

class JsonPersistenceManager implements Persistence {
}

class EntitiesAndComponentsManager {
}

class SystemsManager {
}

LevelDesignerViewModel *-- Persistence
GameViewModel *-- Persistence
GameViewModel *-- Renderer
GameViewModel *-- EntitiesAndComponentsManager
GameViewModel *-- SystemsManager

@enduml