@startuml
class LevelDesignerViewModel {
}

class GameViewModel {
}

class Renderer {
}

protocol Persistence {
    +saveLevel(level: Level)
    +loadLevel(levelName: string): Level
    +deleteLevel(levelName: string)
}

class JsonPersistenceManager implements Persistence {
}

class EntitiesAndComponentsManager {
    +entities: [GameObject]
    +componentToEntities: [ComponentId: Set<GameObject>]
}

class SystemsManager {
}

class AnimationSystem {
}

class PhysicsSystem {
}

class CollisionSystem {
}

class MovementSystem {
}

LevelDesignerViewModel *-- Persistence
GameViewModel *-- Persistence
GameViewModel *-- Renderer
GameViewModel *-- EntitiesAndComponentsManager
GameViewModel *-- SystemsManager
SystemsManager --> AnimationSystem
SystemsManager --> PhysicsSystem
SystemsManager --> CollisionSystem
SystemsManager --> MovementSystem

@enduml