@startuml
class LevelDesignerViewModel {
    selectedObject: BoardObject
    selectedObjectType: BoardObjectType
}

class Enemy extends BoardObject {
}

class Block extends BoardObject {
}

class Collectible extends BoardObject {
}

class PowerUp extends BoardObject {
}

class Grid {
    contains: BoardObject
}

class Board {
    name: String
    width: Int
    height: Int
}

class Palette {
}

class HealthSetter {
}

class MovementSetter {
}

class DropSetter {
}

class BoardObject {
    center: CGPoint
    width: Int
    height: Int
    objects: [BoardObject]
}

Board *-- "many" Grid
Grid --> BoardObject
Palette *-- HealthSetter
Palette *-- MovementSetter
Palette *-- DropSetter
LevelDesignerViewModel *-- Board
LevelDesignerViewModel *-- Palette
@enduml
